### ISSUE TITLE
Some colours are now back to default discord grey

### ISSUE THREAD

**Issue by EmeraldSnorlax** [rose-pine/discord#3]
```
Canary 110234 (b3cd76f) 
Host 0.0.131 
Linux 64-Bit (5.15.12-Arch1-1)
```

The message box and user tray is grey now. (The theme seemed to work correctly before the client updated?)

![Screenshot_20220108_111035](https://user-images.githubusercontent.com/43452521/148641940-0fcd44c7-1da6-4b40-ad2b-6f8fca8f0aeb.png)

The friends page has also turned grey.

![Screenshot_20220108_111252](https://user-images.githubusercontent.com/43452521/148641974-1c1fc11a-55e8-4f70-be2f-605718d726f1.png)

The same issue happens with Rose Pine dawn / discord light mode -- it uses the discord white colour instead of the sepia for the mentioned components above.

**Comment by ThatOneCalculator** [comment]
Fixed. Discord hates themers lmao

**Comment by archer-65** [comment]
> Fixed. Discord hates themers lmao

Hi, I know you've just closed the issue, but the "Friend Page" is still Grey

![image](https://user-images.githubusercontent.com/76066109/149045470-dd231b6e-c238-414c-8c6e-2f0840fecfc3.png)

**Comment by ThatOneCalculator** [comment]
:thinking: ![Screenshot_2022-01-11-06-44-40_2560x1440](https://user-images.githubusercontent.com/44733677/149054521-af7475d5-9b7a-43ed-93b2-ee0e78c78802.png)

**Comment by EmeraldSnorlax** [comment]
well uh, this is interesting...
i just got home and copied the new css down, hard refreshed my client, and the friends page is still grey.

the message box is the correct colour again, but the friends page is still the same grey...

**Comment by ThatOneCalculator** [comment]
@EmeraldSnorlax should be entirely fixed now. Re-copy the CSS

**Comment by EmeraldSnorlax** [comment]
getting closer, but no cigar >.>

![image](https://user-images.githubusercontent.com/43452521/149367228-1a8624c9-4aa4-4b3b-bc08-e9a42301100b.png)

![image](https://user-images.githubusercontent.com/43452521/149367283-b164da5b-5354-4214-9404-f1da2f11e7a5.png)

the area around the search bar is still discord default grey / white


```
Canary 110795 (a58eddb)
Host 0.0.132
Linux 64-Bit (5.15.13-Arch1-1)
Powercord v2 (29a69f9)
```

**Comment by ThatOneCalculator** [comment]
Again, not getting that on my end, so there's nothing I can do to try and fix it. If you wanna give it a go yourself, we'd love to take a PR.
